version: '3.8'

services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
    ports:
      - "8080:8080" 
      - "7077:7077" 
    networks:
      - spark-network

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    networks:
      - spark-network

  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    image: airflow-docker
    container_name: airflow
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////usr/local/airflow/airflow.db
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    ports:
      - "8081:8080"
    volumes:
      - ./data:/usr/local/airflow/data
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge